### ISSUE TITLE
feat: Display multiple tasks using multicall to reduce provider calls

### ISSUE THREAD

**Issue by nomadbitcoin** [w3b3d3v/web3task-front#13]

**Comment by 0xneves** [comment]
Context:
The task manager comes with a contract that casts a multi-call, those are used to batch together multiple function calls.
When we are working with the front-end, doing too many function calls to the blockchain, even though it's read-only, will depend on the proficiency of the front-end code and the provider speed, as well as the user's internet speed.

Problem:
When searching for 20 NFTs data to be displayed on a single page, the average loading time will be around ~2 seconds for each on a good day. Since we'll be using the user-connected provider, those calls might even get blocked and correct typings should be made to make it handle errors and malfunctions.

Proposed Solution: (assuming we want to fetch the task ids 1 to 20 to display in main screen)
We batch a call using

```
abi.encodeWithSelector("getTask(uint256)", [1])
```

This is a solidity function, in ethers we can find it by loading an instance of the contract and calling:
(this example is from ENS)
```
contract.interface.encodeFunctionData('setText', [
        namehash('newconfigname.eth'),
        'url',
        'ethereum.com',
      ]),
```

So to prepare the data using typescript for the getTask function, it should be something like:
Note that this is only the instance already loaded.
```
bytes payload = contract.interface.encodeFunctionData('geTask', [1,]),
```

This should be used in a for loop to fetch the payload for all 20 transactions which will return tasks properly.
All payloads should be inside an array of the actual transaction to be sent.
```
for(var i = 0; i < 20; i++){
      bytes[] payload = contract.interface.encodeFunctionData('geTask', [i]);
}

// We then call the multicall function
const result = await contract.multicall(payload);
```

Thats it! Now the result variable will carry an array with all the 20's results. If it fails, we should just keep forcing until the public providers indexes and shares the result with us correctly.

Obs: When fetching data for the profile, we should first call:
```
const result = await contract.getUserTasks(wallet.address)
```
To retrieve all the tasks that user has.
Then we repeat the same solution steps to build the task page profile, totaling only 2 transactions.

**Comment by 0xneves** [comment]
#06015478f3b752cb57e80f5ea7dfdeb8942df58b

Implemented this feature on the contracts side.

Must apply to the front-end at the TASK PAGE and the TASK PROFILE

**Comment by heronlancellot** [comment]
Implemented this feature apply to frontend ( CardMultiTasks, CardTasks )

**Comment by 0xneves** [comment]
This pull request is a subset that should be reviewed prior to this issue

[#16](https://github.com/w3b3d3v/web3task-contracts/pull/16)
