### ISSUE TITLE
refactor: change phrase to describe end date of task

### ISSUE THREAD

**Issue by 0xneves** [w3b3d3v/web3task-front#155]
The description of the end date component will not change regardless of the timestamp. The button is not the best button as well and could use a little make up!
![Image](https://github.com/w3b3d3v/web3task-front/assets/90667119/ed7f10c9-c971-4e07-8d0b-67b403fcb784)

Proposal:
- Change "Ending" into "Ended" after the task has been completed or expired.
- Change the button colors and overall design to something that communicates better with the other components. Show us your inner artist!
- Post the button design result in this issue or in the PR response.

**Comment by RafaDSan** [comment]
I am working on this task!

**Comment by RafaDSan** [comment]
I've changed the button to be red when the task is canceled and to be green when the task is completed, besides the message showing as "Ended" instead of "Ending" what do you think?

Img 1
![Image](https://github.com/w3b3d3v/web3task-front/assets/102108966/4f4ee872-0a85-40d4-8b11-b068509e3490)


Img 2
![Image](https://github.com/w3b3d3v/web3task-front/assets/102108966/c58f9a64-1afb-42ee-8758-5f30e2172ba1)

**Comment by RafaDSan** [comment]
Hey, @0xneves What do you think of the changes? Do you want to see anything else or change something?

**Comment by 0xneves** [comment]
@RafaDSan  Awesome additions! This issue was not being tracked in the dashboard as in-progress so I skipped, thank you for updating it Sir!

**Comment by RafaDSan** [comment]
Thank you for your feedback! I'll do the PR then :)
